### ISSUE TITLE
Envelope Message Payload Format v1

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube2-Meta-RFC#1]
## Abstract

Envelope Message Payload Format (ENPF) is designed to be a robust format which can endure many manipulations through the transportation procedures over other messaging applications.

## Structure

The whole message is a JSON dictionary, which is later Base64url encoded or BaseHanzi encoded for transportation safety. Every element of the array represents a data field. If a data field is deprecated in a later version, it should be left blank, thus JSON interpreters will treat it as `undefined`.

One message should have only one AES key for all AES operations. The AES algorithm should be /* RFF @yisiliu */.

Key | Type | Description
--- | --- | ---
0 | Number | Version number, now `0`
1 | Number | UNIX Timestamp
2 | String | AES-encrypted ciphertext, Base64 encoded
3 | Array | A list of ephemeral public keys, each being formatted as [KRB58H](https://github.com/neruthes/PKI-QAQ/issues/2)
4 | Array | A list of Base64-encoded ciphertext, each being an EDCH ciphertext of the AES key
5 | Array | A list of Instance Keys of AES-encrypted recipients, each being an Base64-encoded AES-encrypted ciphertext of [KRI](https://github.com/neruthes/PKI-QAQ/issues/4) where the [KeyUsage](https://github.com/neruthes/PKI-QAQ/issues/9) of the Instance Key must include `tessercube.com` or `xx-all`

**Comment by jk234ert** [comment]
My stupid 1st question: why not a **JSON Dictionary** for better compatibility?

**Comment by neruthes** [comment]
> My stupid 1st question: why not a **JSON Dictionary** for better compatibility?

"reduce bytes used"

<img width="658" alt="Screen Shot 2019-10-23 at 12 54 14" src="https://user-images.githubusercontent.com/2139261/67467487-55d2f180-f638-11e9-9bb3-07370089693b.png">

**Comment by jk234ert** [comment]
> > My stupid 1st question: why not a **JSON Dictionary** for better compatibility?
> 
> "reduce bytes used"
> 
> <img alt="Screen Shot 2019-10-23 at 12 54 14" width="658" src="https://user-images.githubusercontent.com/2139261/67467487-55d2f180-f638-11e9-9bb3-07370089693b.png">

Splendid example, but webpack would obfuscate all var/func names I guess?

**Comment by MainasuK** [comment]
https://github.com/protocolbuffers/protobuf

reduce bytes used (real)

**Comment by jk234ert** [comment]
One Commonly used format in IM protocols:
ProtoBuf -> encrypt mechanism -> compress

**Comment by yisiliu** [comment]
> One Commonly used format in IM protocols:
> ProtoBuf -> encrypt mechanism -> compress

really helpful suggestions!!!!!

**Comment by neruthes** [comment]
This draft is suspended. See new draft at https://github.com/DimensionDev/Tessercube2-Meta-RFC/issues/3
